### ISSUE TITLE
Android dex-related crash when serializing the Transaction class 

### ISSUE THREAD

**Issue by creativedrewy** [metaplex-foundation/solana-kmp#50]
The Transaction class can't seem to find `BufferFactoryJvm` when attempting to serialize on Android.

The code that produces the crash (running on Android):

```
val tx = SolanaTransactionBuilder()
                    .addInstruction(MemoProgram.writeUtf8(publicKey, memoText))
                    .setRecentBlockHash(blockHash)
                    .build() as SolanaTransaction

                tx.feePayer = conn.publicKey
                val bytes = tx.serialize(SerializeConfig(requireAllSignatures = false))
```

The stack trace:

```
Process: com.solanamobile.ktxclientsample, PID: 20094
                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ditchoom/buffer/BufferFactoryJvm;
                 	at foundation.metaplex.solana.transactions.SolanaMessage.serialize(SolanaMessage.kt:93)
                 	at foundation.metaplex.solana.transactions.SolanaTransaction.serializeMessage(SolanaTransaction.kt:330)
                 	at foundation.metaplex.solana.transactions.SolanaTransaction.serialize(SolanaTransaction.kt:337)
                 	at com.solanamobile.ktxclientsample.viewmodel.SampleViewModel$publishMemo$1.invokeSuspend(SampleViewModel.kt:167)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7944)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@538de12, Dispatchers.Main.immediate]
                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ditchoom.buffer.BufferFactoryJvm" on path: DexPathList[[dex file "/data/data/com.solanamobile.ktxclientsample/code_cache/.overlay/base.apk/classes14.dex", zip file "/data/app/~~Jtm7M-bCAWGhwcFGEB-v6g==/com.solanamobile.ktxclientsample-iiNGA3Rpdlxe5teFOe_8Hw==/base.apk"],nativeLibraryDirectories=[/data/app/~~Jtm7M-bCAWGhwcFGEB-v6g==/com.solanamobile.ktxclientsample-iiNGA3Rpdlxe5teFOe_8Hw==/lib/arm64, /data/app/~~Jtm7M-bCAWGhwcFGEB-v6g==/com.solanamobile.ktxclientsample-iiNGA3Rpdlxe5teFOe_8Hw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by iamvon** [comment]
I'm not sure if anyone else is having this issue in 2025, but here's my solution in my KMP project for those interested.

When using this Metaplex Solana-KMP library in Android, I encountered a similar error:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ditchoom/buffer/BufferFactoryJvm;
at foundation.metaplex.solana.transactions.SolanaMessage.serialize
```
## Solution

The issue occurs because the `solana-kmp` library relies on the JVM version of the `buffer` library, but Android builds typically use the Android-specific version.

### 1. Add `buffer-jvm` to dependencies in `gradle/libs.versions.toml`:

```toml
[versions]
buffer = "1.4.2"

[libraries]
buffer-jvm = { module = "com.ditchoom:buffer-jvm", version.ref = "buffer" }
```

### 2. Configure Android to use the `buffer-jvm` library and exclude the Android variant in `shared/build.gradle.kts`:

```kotlin
android {
    // Other configurations...

    dependencies {
        implementation(libs.buffer.jvm)
    }

    configurations {
        implementation {
            resolutionStrategy.force(libs.buffer.jvm)
        }
        all {
            exclude(group = "com.ditchoom", module = "buffer-android")
        }
    }
}
```

This ensures the JVM implementation is used and prevents duplicate class conflicts with the Android implementation.

**Comment by JOJO-zsy** [comment]
> I'm not sure if anyone else is having this issue in 2025, but here's my solution in my KMP project for those interested.
> 
> When using this Metaplex Solana-KMP library in Android, I encountered a similar error:
> 
> ```
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ditchoom/buffer/BufferFactoryJvm;
> at foundation.metaplex.solana.transactions.SolanaMessage.serialize
> ```
> 
> ## Solution
> The issue occurs because the `solana-kmp` library relies on the JVM version of the `buffer` library, but Android builds typically use the Android-specific version.
> 
> ### 1. Add `buffer-jvm` to dependencies in `gradle/libs.versions.toml`:
> [versions]
> buffer = "1.4.2"
> 
> [libraries]
> buffer-jvm = { module = "com.ditchoom:buffer-jvm", version.ref = "buffer" }
> ### 2. Configure Android to use the `buffer-jvm` library and exclude the Android variant in `shared/build.gradle.kts`:
> android {
>     // Other configurations...
> 
>     dependencies {
>         implementation(libs.buffer.jvm)
>     }
> 
>     configurations {
>         implementation {
>             resolutionStrategy.force(libs.buffer.jvm)
>         }
>         all {
>             exclude(group = "com.ditchoom", module = "buffer-android")
>         }
>     }
> }
> This ensures the JVM implementation is used and prevents duplicate class conflicts with the Android implementation.

I can’t thank you enough—you saved my life.
